IF NOT EXISTS (SELECT 1 FROM sys.schemas AS s WHERE s.name = 'auth')
BEGIN
    DECLARE @sql VARCHAR(21);
    SET @sql = 'CREATE SCHEMA [auth]';
    EXEC(@sql);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.schemas AS s WHERE s.name = 'history')
BEGIN
    DECLARE @sql VARCHAR(24);
    SET @sql = 'CREATE SCHEMA [history]';
    EXEC(@sql);
END;
GO

IF NOT EXISTS (SELECT 1 FROM sys.databases AS d WHERE d.name = DB_NAME() AND d.is_temporal_history_retention_enabled = 1)
BEGIN
    DECLARE @sql VARCHAR(178);
    SET @sql = 'ALTER DATABASE ' + DB_NAME() + ' SET TEMPORAL_HISTORY_RETENTION ON';
    EXEC(@sql);
END;
GO

/********************************************************************
*   [auth].[USER]
********************************************************************/

CREATE TABLE [auth].[USER] (
    ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    USER_LOGIN VARCHAR(10) NOT NULL,
    CREATED_DATETIME DATETIME2 DEFAULT SYSUTCDATETIME(),
    MODIFIED_DATETIME DATETIME2 DEFAULT SYSUTCDATETIME(),
    IS_ACTIVE BIT DEFAULT 1,
    VALIDFROM DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT DF_USER_InsurancePolicy_ValidFrom DEFAULT SYSUTCDATETIME(),
    VALIDTO DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN CONSTRAINT DF_USER_InsurancePolicy_ValidTo DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
    CONSTRAINT UQ_USER_USER_LOGIN UNIQUE(USER_LOGIN),
    CONSTRAINT CK_USER_CREATE_BEFORE_MODIFY CHECK(CREATED_DATETIME <= MODIFIED_DATETIME),
    PERIOD FOR SYSTEM_TIME(VALIDFROM, VALIDTO)
)
WITH (SYSTEM_VERSIONING = ON
    (
        HISTORY_TABLE = [history].[USER_HISTORY],
        HISTORY_RETENTION_PERIOD = INFINITE
    )
);
GO

/********************************************************************
*   [dbo].[USERREQUEST]
********************************************************************/

CREATE TABLE [dbo].[USERREQUEST] (
    ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    USER_ID UNIQUEIDENTIFIER NOT NULL,
    REQUEST NVARCHAR(MAX) NOT NULL,
    CREATED_DATETIME DATETIME2 DEFAULT SYSUTCDATETIME(),
    VALIDFROM DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT DF_USERREQUEST_InsurancePolicy_ValidFrom DEFAULT SYSUTCDATETIME(),
    VALIDTO DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN CONSTRAINT DF_USERREQUEST_InsurancePolicy_ValidTo DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
    CONSTRAINT FK_USERREQUEST_USER FOREIGN KEY (USER_ID) REFERENCES [auth].[USER](ID),
    PERIOD FOR SYSTEM_TIME(VALIDFROM, VALIDTO)
)
WITH (SYSTEM_VERSIONING = ON
    (
        HISTORY_TABLE = [history].[USERREQUEST_HISTORY],
        HISTORY_RETENTION_PERIOD = 1 YEAR
    )
);
GO

/********************************************************************
*   [dbo].[AIENGINERESPONSE]
********************************************************************/

CREATE TABLE [dbo].[AIENGINERESPONSE] (
    ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    USER_ID UNIQUEIDENTIFIER NOT NULL,
    USERREQUEST_ID UNIQUEIDENTIFIER NOT NULL,
    ANSWER NVARCHAR(MAX) NOT NULL,
    RATING BIT NULL,
    CREATED_DATETIME DATETIME2 DEFAULT SYSUTCDATETIME(),
    MODIFIED_DATETIME DATETIME2 DEFAULT SYSUTCDATETIME(),
    VALIDFROM DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN CONSTRAINT DF_USER_InsurancePolicy_ValidFrom DEFAULT SYSUTCDATETIME(),
    VALIDTO DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN CONSTRAINT DF_USER_InsurancePolicy_ValidTo DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
    CONSTRAINT FK_AIENGINERESPONSE_USER FOREIGN KEY (USER_ID) REFERENCES [auth].[USER](ID),
    CONSTRAINT FK_AIENGINERESPONSE_USERREQUEST FOREIGN KEY (USERREQUEST_ID) REFERENCES [dbo].[USERREQUEST](ID),
    PERIOD FOR SYSTEM_TIME(VALIDFROM, VALIDTO)
)
WITH (SYSTEM_VERSIONING = ON
    (
        HISTORY_TABLE = [history].[AIENGINERESPONSE_HISTORY],
        HISTORY_RETENTION_PERIOD = 1 YEAR
    )
);
GO
